In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
%pwd

'C:\\Users\\Alex Loftus\\Dropbox\\Programming\\Projects\\Jupyter-Notebooks\\Analyses\\Seattle police dataset'

In [9]:
df = pd.read_csv('../../datasets/Seattle-Police-Reports.csv')
df.head()

,RMS CDW ID,General Offense Number,Offense Code,Offense Code Extension,Offense Type,Summary Offense Code,Summarized Offense Description,Date Reported,Occurred Date or Date Range Start,Occurred Date Range End,Hundred Block Location,District/Sector,Zone/Beat,Census Tract 2000,Longitude,Latitude,Location,Month,Year
0,1032236,2012163025,2303,0,THEFT-SHOPLIFT,2300,SHOPLIFTING,05/26/2012 08:20:00 PM,05/26/2012 08:20:00 PM,NaN,1XX BLOCK OF MERCER ST,Q,Q3,7000.3021,-122.354752,47.624577,"(47.624576569, -122.354751587)",5,2012
1,1032237,2012198841,2399,3,THEFT-OTH,2300,OTHER PROPERTY,06/24/2012 05:29:00 PM,06/24/2012 03:30:00 PM,NaN,3XX BLOCK OF HARRISON ST,Q,Q3,7100.2001,-122.350853,47.622086,"(47.622085571, -122.350852966)",6,2012
2,1032238,201472111,2404,8,VEH-THEFT-TRUCK,2400,VEHICLE THEFT,03/08/2014 06:57:00 AM,03/07/2014 10:00:00 PM,03/08/2014 06:30:00 AM,CHERRY ST / 2 AV,K,K1,8100.2036,-122.333176,47.603016,"(47.6030159, -122.333175659)",3,2014
3,1032239,2014107311,2202,0,BURGLARY-FORCE-RES,2200,BURGLARY,04/08/2014 03:59:00 PM,04/08/2014 10:30:00 AM,04/08/2014 03:59:00 PM,130XX BLOCK OF 25 AV NE,L,L1,200.2001,-122.301888,47.723846,"(47.723846436, -122.301887512)",4,2014
4,1032241,2014123990,2404,1,VEH-THEFT-AUTO,2400,VEHICLE THEFT,04/23/2014 08:29:00 AM,04/22/2014 06:15:00 PM,04/23/2014 08:25:00 AM,22XX BLOCK OF NW 64 ST,B,B1,3300.4006,-122.386162,47.675289,"(47.675289154, -122.386161804)",4,2014