# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

In [73]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/jokecamp/FootballData/master/UEFA_European_Championship/Euro%202012/Euro%202012%20stats%20TEAM.csv).

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/jokecamp/FootballData/master/UEFA_European_Championship/Euro%202012/Euro%202012%20stats%20TEAM.csv')

In [83]:
df.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Step 3. Assign it to a variable called euro12.

In [5]:
# kayyyy

### Step 4. Select only the Goal column.

In [6]:
df.Goals

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [8]:
df.Team.count()

16

### Step 6. What is the number of columns in the dataset?

In [11]:
len(df.columns)

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [20]:
disc = df[['Team', 'Yellow Cards', 'Red Cards']].copy()
disc.head()

             Team  Yellow Cards  Red Cards
0         Croatia             9          0
1  Czech Republic             7          0
2         Denmark             4          0
3         England             5          0
4          France             6          0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [21]:
disc.sort_values(['Red Cards', 'Yellow Cards'], ascending=False, inplace=True)
disc.head()

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0

In [19]:
df.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Step 9. Calculate the mean Yellow Cards given per Team

In [40]:
df.groupby('Team')['Yellow Cards'].mean()

Team
Croatia                 9
Czech Republic          7
Denmark                 4
England                 5
France                  6
Germany                 4
Greece                  9
Italy                  16
Netherlands             5
Poland                  7
Portugal               12
Republic of Ireland     6
Russia                  6
Spain                  11
Sweden                  7
Ukraine                 5
Name: Yellow Cards, dtype: int64

### Step 10. Filter teams that scored more than 6 goals

In [43]:
df[df['Goals'] > 6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

### Step 11. Select the teams that start with G

In [46]:
df[df.Team.str.startswith('G')]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

### Step 12. Select the first 7 columns

In [48]:
df.iloc[:, :7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4,13,12,51.9%,16.0%,32
1,Czech Republic,4,13,18,41.9%,12.9%,39
2,Denmark,4,10,10,50.0%,20.0%,27
3,England,5,11,18,50.0%,17.2%,40
4,France,3,22,24,37.9%,6.5%,65
5,Germany,10,32,32,47.8%,15.6%,80
6,Greece,5,8,18,30.7%,19.2%,32
7,Italy,6,34,45,43.0%,7.5%,110
8,Netherlands,2,12,36,25.0%,4.1%,60
9,Poland,2,15,23,39.4%,5.2%,48
10,Portugal,6,22,42,34.3%,9.3%,82
11,Republic of Ireland,1,7,12,36.8%,5.2%,28
12,Russia,5,9,31,22.5%,12.5%,59
13,Spain,12,42,33,55.9%,16.0%,100
14,Sweden,5,17,19,47.2%,13.8%,39
15,Ukraine,2,7,26,21.2%,6.0%,38

### Step 13. Select all columns except the last 3.

In [63]:
df.iloc[:, :-3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,0,4,4,13,76.5%,48,31,4,5,0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [62]:
df.set_index('Team').loc[['England', 'Italy', 'Russia']]['Shooting Accuracy']

Team
England    50.0%
Italy      43.0%
Russia     22.5%
Name: Shooting Accuracy, dtype: object

In [60]:
df[df.Team.isin(['England', 'Italy', 'Russia'])]['Shooting Accuracy']

3     50.0%
7     43.0%
12    22.5%
Name: Shooting Accuracy, dtype: object

In [64]:
df.loc[df.Team.isin(['England', 'Italy', 'Russia']), ['Team', 'Shooting Accuracy']]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

In [71]:
sns.load_dataset('brain_networks').head()

,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
0,node,1,1,1,1,1,1,1,1,1,...,3,4,4,1,1,2,2,3,3,4
1,hemi,lh,rh,lh,rh,lh,rh,lh,rh,lh,...,rh,lh,rh,lh,rh,lh,rh,lh,rh,lh
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,56.05574417114258,92.03103637695312,3.391575574874878,38.65968322753906,26.203819274902344,-49.71556854248047,47.4610366821289,26.746612548828125,-35.898860931396484,...,0.6079040169715881,-70.27054595947266,77.36577606201172,-21.73455047607422,1.0282527208328247,7.7917842864990225,68.90372467041016,-10.520872116088867,120.49046325683594,-39.686431884765625
4,1,55.5472526550293,43.6900749206543,-65.49598693847656,-13.974522590637207,-28.27496337890625,-39.05012893676758,-1.2106596231460571,-19.012897491455078,19.568010330200195,...,57.49507141113281,-76.39321899414062,127.26136016845705,-13.035799026489258,46.3818244934082,-15.752449989318848,31.00033187866211,-39.607521057128906,24.76401138305664,-36.7710075378418

In [72]:
sns.load_dataset('fmri')

     subject  timepoint event    region    signal
0        s13         18  stim  parietal -0.017552
1         s5         14  stim  parietal -0.080883
2        s12         18  stim  parietal -0.081033
3        s11         18  stim  parietal -0.046134
4        s10         18  stim  parietal -0.037970
5         s9         18  stim  parietal -0.103513
6         s8         18  stim  parietal -0.064408
7         s7         18  stim  parietal -0.060526
8         s6         18  stim  parietal -0.007029
9         s5         18  stim  parietal -0.040557
10        s4         18  stim  parietal -0.048812
11        s3         18  stim  parietal -0.047148
12        s2         18  stim  parietal -0.086623
13        s1         18  stim  parietal -0.046659
14        s0         18  stim  parietal -0.075570
15       s13         17  stim  parietal -0.008265
16       s12         17  stim  parietal -0.088512
17        s7          9  stim  parietal  0.058897
18       s10         17  stim  parietal -0.016847
19        s9         17  stim  parietal -0.121574
20        s8         17  stim  parietal -0.076287
21        s7         17  stim  parietal -0.043812
22        s6         17  stim  parietal -0.014746
23        s5         17  stim  parietal -0.056682
24        s4         17  stim  parietal -0.044582
25        s3         17  stim  parietal -0.053514
26        s2         17  stim  parietal -0.077292
27        s1         17  stim  parietal -0.038021
28        s0         17  stim  parietal -0.071300
29       s13         16  stim  parietal -0.002856
...      ...        ...   ...       ...       ...
1034      s5         13   cue   frontal -0.014985
1035      s4         13   cue   frontal -0.021514
1036      s3         13   cue   frontal -0.047639
1037      s2         13   cue   frontal  0.047918
1038      s1         13   cue   frontal  0.028379
1039      s0         13   cue   frontal -0.021729
1040     s13         12   cue   frontal -0.020686
1041     s12         12   cue   frontal -0.003034
1042     s11         12   cue   frontal  0.055766
1043     s10         12   cue   frontal  0.005711
1044      s9         12   cue   frontal  0.024292
1045      s7         12   cue   frontal -0.014005
1046      s2          7   cue   frontal -0.078363
1047     s10         10   cue   frontal -0.016124
1048      s8         10   cue   frontal -0.015141
1049     s10          8   cue   frontal -0.052505
1050      s9          8   cue   frontal -0.008729
1051      s8          8   cue   frontal  0.007278
1052      s7          8   cue   frontal  0.015765
1053      s6          8   cue   frontal -0.063961
1054      s5          8   cue   frontal -0.028292
1055      s4          8   cue   frontal -0.160821
1056      s3          8   cue   frontal -0.033848
1057      s2          8   cue   frontal -0.069666
1058      s1          8   cue   frontal -0.136059
1059      s0          8   cue   frontal  0.018165
1060     s13          7   cue   frontal -0.029130
1061     s12          7   cue   frontal -0.004939
1062     s11          7   cue   frontal -0.025367
1063      s0          0   cue  parietal -0.006899

[1064 rows x 5 columns]